version: "3.9"
services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - app
    volumes:
      - ./:/var/www/html
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./:/var/www/html
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    ports:
      - "3000:8080"
    volumes:
      - ./frontend/:/frontend
    tty: true
    command: bash -c "cd /frontend && yarn run serve"
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
      TZ: "Asia/Tokyo"
    volumes:
      - ./docker/db/data:/var/lib/mysql
    ports:
      - 3306:3306
    platform: linux/amd64
